/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function optimizesinglewasm_optimize(a: number, b: number): number;
export function calculatorinterface_get_damage_analysis(a: number, b: number): number;
export function calculatorinterface_get_transformative_damage(a: number): number;
export function teamoptimizationwasm_optimize_team2(a: number, b: number): number;
export function __wbg_optimizesinglewasm_free(a: number): void;
export function __wbg_calculatorinterface_free(a: number): void;
export function __wbg_teamoptimizationwasm_free(a: number): void;
export function commoninterface_get_attribute(a: number): number;
export function commoninterface_get_artifacts_rank_by_character(a: number, b: number, c: number, d: number): number;
export function bonusperstat_bonus_per_stat(a: number): number;
export function potentialinterface_get_potential(a: number, b: number): number;
export function calcartifactbestset_calc_artifact_best_set(a: number): number;
export function __wbg_commoninterface_free(a: number): void;
export function __wbg_bonusperstat_free(a: number): void;
export function __wbg_potentialinterface_free(a: number): void;
export function __wbg_calcartifactbestset_free(a: number): void;
export function dslinterface_run(a: number, b: number, c: number, d: number): number;
export function __wbg_dslinterface_free(a: number): void;
export function __wbg_transformativedamage_free(a: number): void;
export function __wbg_get_transformativedamage_swirl_cryo(a: number): number;
export function __wbg_set_transformativedamage_swirl_cryo(a: number, b: number): void;
export function __wbg_get_transformativedamage_swirl_hydro(a: number): number;
export function __wbg_set_transformativedamage_swirl_hydro(a: number, b: number): void;
export function __wbg_get_transformativedamage_swirl_pyro(a: number): number;
export function __wbg_set_transformativedamage_swirl_pyro(a: number, b: number): void;
export function __wbg_get_transformativedamage_swirl_electro(a: number): number;
export function __wbg_set_transformativedamage_swirl_electro(a: number, b: number): void;
export function __wbg_get_transformativedamage_overload(a: number): number;
export function __wbg_set_transformativedamage_overload(a: number, b: number): void;
export function __wbg_get_transformativedamage_electro_charged(a: number): number;
export function __wbg_set_transformativedamage_electro_charged(a: number, b: number): void;
export function __wbg_get_transformativedamage_shatter(a: number): number;
export function __wbg_set_transformativedamage_shatter(a: number, b: number): void;
export function __wbg_get_transformativedamage_superconduct(a: number): number;
export function __wbg_set_transformativedamage_superconduct(a: number, b: number): void;
export function __wbg_get_transformativedamage_bloom(a: number): number;
export function __wbg_set_transformativedamage_bloom(a: number, b: number): void;
export function __wbg_get_transformativedamage_hyperbloom(a: number): number;
export function __wbg_set_transformativedamage_hyperbloom(a: number, b: number): void;
export function __wbg_get_transformativedamage_burgeon(a: number): number;
export function __wbg_set_transformativedamage_burgeon(a: number, b: number): void;
export function __wbg_get_transformativedamage_burning(a: number): number;
export function __wbg_set_transformativedamage_burning(a: number, b: number): void;
export function __wbg_get_transformativedamage_crystallize(a: number): number;
export function __wbg_set_transformativedamage_crystallize(a: number, b: number): void;
export function __wbindgen_export_0(a: number, b: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number, d: number): number;
export function __wbindgen_export_2(a: number, b: number, c: number): void;
export function __wbindgen_export_3(a: number): void;
