use serde::{Deserialize, Serialize};

fn full_coverage() -> f64 { 1.0 }

#[derive(Serialize, Deserialize)]
pub enum WeaponConfig {
    AthameArtis { burst_hit: bool, secret_rite: bool, #[serde(default = "full_coverage")] rate: f64 },
    MoonweaverDawn { energy_cost: usize },
    SerenitysCall { reaction_active: bool, moon_full: bool, #[serde(default = "full_coverage")] rate: f64 },
    LightbearingMoonshard { skill_active: bool, #[serde(default = "full_coverage")] rate: f64 },
    WhitelakeFrostfeather { stacks: f64, #[serde(default = "full_coverage")] rate: f64 },
    ExaiphanesBlade { hit_active: bool, #[serde(default = "full_coverage")] rate: f64, #[serde(default)] resonated_elements: i32 },
    AmberBead { stacks: f64 },
    NightweaversLookingGlass { skill_active: bool, lunar_bloom_active: bool, #[serde(default = "full_coverage")] skill_rate: f64, #[serde(default = "full_coverage")] lunar_rate: f64 },
    ReliquaryOfTruth { skill_active: bool, lunar_bloom_hit: bool, #[serde(default = "full_coverage")] skill_rate: f64, #[serde(default = "full_coverage")] lunar_rate: f64 },
    DawningFrost { charged_active: bool, skill_active: bool, #[serde(default = "full_coverage")] charged_rate: f64, #[serde(default = "full_coverage")] skill_rate: f64 },
    EtherlightSpindlelute { skill_active: bool, #[serde(default = "full_coverage")] rate: f64 },
    BlackmarrowLantern { moon_full: bool },
    NocturnesCurtainCall { lunar_active: bool, #[serde(default = "full_coverage")] rate: f64 },
    AngelosHeptades { shield_active: bool, #[serde(default = "full_coverage")] rate: f64 },
    NewBough { stacks: f64, radiance: bool, rate: f64 },
    WintersHeavyHeart { cryo_count: usize, electro_count: usize, radiance: bool, #[serde(default = "full_coverage")] rate: f64 },
    BreezeborneRefrain { rate: f64 },
    HereticsMoltenBlade { movement_rate: f64, #[serde(default = "full_coverage")] rate: f64 },
    Emberwell {
        reaction_active: bool, stellar_active: bool,
        #[serde(default = "full_coverage")] reaction_rate: f64,
        #[serde(default = "full_coverage")] stellar_rate: f64,
    },
    ForgedByTheGoldenMelody {
        state: usize, counterpoint_active: bool, #[serde(default)] counterpoint_state: usize,
        #[serde(default = "full_coverage")] rate: f64,
        #[serde(default = "full_coverage")] counterpoint_rate: f64,
    },
    BladeOfAtonement {
        reaction_active: bool, stellar_active: bool,
        #[serde(default = "full_coverage")] reaction_rate: f64,
        #[serde(default = "full_coverage")] stellar_rate: f64,
    },
    Frostbreath {
        active: bool,
        #[serde(default = "full_coverage")] rate: f64,
        #[serde(default = "full_coverage")] energy_rate: f64,
    },
    SongOfTheVigil {
        stellar_active: bool,
        #[serde(default = "full_coverage")] rate: f64,
        #[serde(default = "full_coverage")] energy_rate: f64,
    },
    ClashOfKings { active: bool, #[serde(default = "full_coverage")] rate: f64 },
    EchoesOfTheHeart {
        reaction_active: bool, stellar_active: bool,
        #[serde(default = "full_coverage")] reaction_rate: f64,
        #[serde(default = "full_coverage")] stellar_rate: f64,
    },
    JadeVista { same_count: usize, diff_count: usize, #[serde(default = "full_coverage")] rate: f64 },
    CovenantOfFrostAndSnow { active: bool, #[serde(default = "full_coverage")] rate: f64 },
    BeyondTheChrysalis {
        #[serde(default)] loyal_wind: bool,
        #[serde(default)] rebel_wind: bool,
        on_field: bool,
        #[serde(default)] loyal_rate: Option<f64>,
        #[serde(default)] rebel_rate: Option<f64>,
        #[serde(default)] plenty_rate: f64,
    },
    HymnOfTheMaelstrom { stacks: usize, boosted: bool, on_field: bool, #[serde(default)] hp: f64 },
    NoConfig,

    // sword
    MistsplitterReforged { emblem_level: usize },
    SummitShaper { stack: f64, shield_rate: f64 },
    FreedomSworn { rate: f64 },
    TheAlleyFlash { rate: f64 },
    PrototypeRancour { stack: f64 },
    LionsRoar { rate: f64 },
    IronSting { stack: f64 },
    CinnabarSpindle { rate: f64 },
    BlackcliffLongsword { stack: f64 },
    HarbingerOfDawn { rate: f64 },
    SkyriderSword { rate: f64 },
    DarkIronSword { rate: f64 },
    CoolSteel { rate: f64 },
    HaranGeppakuFutsu { stack: f64 },
    CursedBlade { rate: f64 },
    SapwoodBlade { rate: f64 },
    XiphosMoonlight { rate: f64 },
    KeyOfKhajNisut { stack: f64, rate: f64 },
    ToukabouShigure { rate: f64 },
    LightOfFoliarIncision { rate: f64 },
    WolfFang { e_stack: f64, q_stack: f64 },
    FinaleOfTheDeep { rate1: f64, rate2: f64 },
    FleuveCendreFerryman { rate: f64 },
    TheDockhandsAssistant { stack: f64 },
    SplendorOfTranquilWaters { stack1: f64, stack2: f64 },
    UrakuMisugiri { rate: f64 },
    Absolution { stack: f64 },
    FluteOfEzpitzal { rate: f64 },
    SturdyBone { rate: f64 },
    PeakPatrolSong { stack: f64, rate: f64 },
    CalamityOfEshu { rate: f64 },
    Azurelight { after_skill: bool, zero_energy: bool },

    // claymore
    WolfsGravestone { rate: f64 },
    TheUnforged { stack: f64, shield_rate: f64 },
    SongOfBrokenPines { rate: f64 },
    Akuoumaru { energy: usize },
    Whiteblind { stack: f64 },
    TheBell { rate: f64 },
    SerpentSpine { stack: f64 },
    BlackcliffSlasher { stack: f64 },
    Rainslasher { rate: f64 },
    LithicBlade { liyue_count: usize },
    SkyriderGreatsword { stack: f64 },
    BloodstainedGreatsword { rate: f64 },
    FerrousShadow { rate: f64 },
    ForestRegalia { rate: f64 },
    MakhairaAquamarine { rate: f64 },
    BeaconOfTheReedSea { rate_atk: f64, rate_hp: f64 },
    MailedFlower { rate: f64 },
    TalkingStick { rate1: f64, rate2: f64 },
    TidalShadow { rate: f64 },
    PortablePowerSaw { stack: f64 },
    UltimateOverlordsMegaMagicSword { rate: f64 },
    Verdict { stack: f64 },
    EarthShaker { rate: f64 },
    FangOfTheMountainKing { stack: f64 },
    FruitfulHook { rate: f64 },
    AThousandBlazingSuns { rate1: f64, rate2: f64 },

    // Polearm
    EngulfingLightning { rate: f64 },
    PrimordialJadeWingedSpear { stack: f64, full_rate: f64 },
    CalamityQueller { stack: f64, backend_rate: f64 },
    StaffOfHoma { be50_rate: f64 },
    VortexVanquisher { stack: f64, shield_rate: f64 },
    PrototypeStarglitter { stack: f64 },
    LithicSpear { liyue_count: usize },
    DragonsBane { rate: f64 },
    Deathmatch { ge2: bool },
    BlackcliffPole { stack: f64 },
    WavebreakersFin { energy: usize },
    BlackTassel { rate: f64 },
    Moonpiercer { rate: f64 },
    MissiveWindspear { rate: f64 },
    StaffOfTheScarletSands { stack: f64 },
    BalladOfTheFjords { use_effect: bool },
    ProspectorsDrill { stack: f64 },
    CrimsonMoonsSemblance { rate1: f64, rate2: f64 },
    LumidouceElegy { stack: f64 },
    FootprintOfTheRainbow { rate: f64 },
    MountainBracingBolt { rate: f64 },
    TamayurateiNoOhanashi { rate: f64 },
    FracturedHalo { after_skill_burst: bool, has_shield: bool },
    SymphonistOfScents { off_field_rate: f64, sweet_echoes_rate: f64 },

    // Catalyst
    LostPrayerToTheSacredWinds { stack: f64 },
    MemoryOfDust { stack: f64, shield_rate: f64 },
    WindAndSong { rate: f64 },
    TheWidsith { t1_rate: f64, t2_rate: f64, t3_rate: f64 },
    SolarPearl { rate1: f64, rate2: f64 },
    MappaMare { stack: f64 },
    DodocoTales { rate1: f64, rate2: f64 },
    BlackcliffAgate { stack: f64 },
    OathswornEye { rate: f64 },
    KagurasVerity { stack: f64, full_rate: f64 },
    MagicGuide { rate: f64 },
    EmeraldOrb { rate: f64 },
    TwinNephrite { rate: f64 },
    FruitOfFulfillment { stack: f64 },
    WanderingEvenstar { rate: f64 },
    AThousandFloatingDreams { same_count: usize, diff_count: usize },
    TulaytullahsRemembrance { stack: f64 },
    JadeFallsSplendor { rate: f64 },
    SacrificialJade { rate: f64 },
    FlowingPurity { rate1: f64, rate2: f64 },
    BalladOfTheBoundlessBlue { stack: f64 },
    CashflowSupervision { stack: f64 },
    TomeOfTheEternalFlow { stack: f64 },
    CranesEchoingCall { rate: f64 },
    RingOfYaxche { rate: f64 },
    SurfsUp { stack: f64 },
    WaveridingWhirl { rate: f64, hydro_count: usize },
    StarcallersWatch { use_buff: bool, rate: f64 },
    SunnyMorningSleepIn { rate1: f64, rate2: f64, rate3: f64 },
    VividNotions { rate1: f64, rate2: f64 },

    // Bow
    PolarStar { stack: usize },
    ThunderingPulse { stack: usize },
    ElegyOfTheEnd { rate: f64 },
    AmosBow { stack: f64 },
    AlleyHunter { stack: f64 },
    Predator { stack: f64 },
    PrototypeCrescent { rate: f64 },
    MouunsMoon { energy: usize },
    MitternachtsWaltz { rate1: f64, rate2: f64 },
    Hamayumi { rate: f64 },
    CompoundBow { stack: f64 },
    BlackcliffWarbow { stack: f64 },
    WindblumeOde { rate: f64 },
    RavenBow { rate: f64 },
    SharpshootersOath { rate: f64 },
    Slingshot { is_effect: bool, rate: f64 },
    AquaSimulacra { is_enemy_around: bool },
    FadingTwilight { state: usize },
    HuntersPath { rate: f64 },
    KingsSquire { rate: f64 },
    IbisPiercer { stack: f64 },
    TheFirstGreatMagic { same_count: f64, diff_count: f64 },
    ScionOfTheBlazingSun { rate: f64 },
    SongOfStillness { rate: f64 },
    RangeGauge { stack: f64 },
    Cloudforged { stack: f64 },
    SilvershowerHeartstrings { stack: f64, stack3_rate: f64 },
    ChainBreaker { count: usize },
    FlowerWreathedFeathers { stack: f64 },
    AstralVulturesCrimsonPlumage { rate: f64, different_count: usize },
}

impl Default for WeaponConfig {
    fn default() -> Self {
        WeaponConfig::NoConfig
    }
}
