import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {LUNAR_CHARACTER_NAMES,LUNAR_CHARACTER_RULES,linneaCatalogHit} from '../beta-data/lunar-character-rules.mjs';
import {EXTENSION_BUFF_REGISTRY,prepareExtensionBuffs} from '../beta-data/extension-buffs.mjs';
import {collectReactionParameters,lunarParameters} from '../beta-data/reaction-parameter-rules.mjs';
import {calculateDirectLunarDamage,calculateLunarCrystallizeTeam} from '../beta-data/lunar-damage.mjs';
import {calculateBloomFamilyDamage} from '../beta-data/bloom-damage.mjs';
import {withLunarDamageContexts} from '../beta-data/lunar-context-facade.mjs';
import {NATIVE_EFFECT_ATTRIBUTES} from '../beta-data/buff-rule-schema.mjs';
const named=(name,p={})=>({name,config:{[name]:p}});
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8*Math.max(1,Math.abs(b)),`${a} != ${b}`);
const input={character:{name:'Vesna'}};
const values=(name,p={},recipient=input)=>EXTENSION_BUFF_REGISTRY.compile(named(name,p),recipient)?.[0]?.config.ExtensionEffect.values||{};
const direct=(kind,buffs=[],more={})=>({kind,owner:{id:'Vesna',em:0,critRate:0,critDamage:0},scalingStat:100,skillMultiplier:1,resistanceMultiplier:1,buffs,...more});
test('1 全部22项注册、来源转换封顶、原始和原生属性一致、满辉与场上限制',()=>{
 assert.equal(LUNAR_CHARACTER_NAMES.length,22);
 const buffs=LUNAR_CHARACTER_NAMES.map(n=>named(n));
 const compiled=prepareExtensionBuffs({...input,buffs}).buffs;
 assert.ok(compiled.every(b=>b.name==='ExtensionEffect'));
 assert.deepEqual(collectReactionParameters(buffs,input),collectReactionParameters(compiled,input));
 assert.deepEqual(collectReactionParameters([...buffs,...compiled],input),collectReactionParameters(buffs,input));
 for(const name of LUNAR_CHARACTER_NAMES)assert.ok(EXTENSION_BUFF_REGISTRY.has(name));
 for(const name of ['IneffaMoonelectroRelay','FlinsTalent1'])near(values(name,{atk:1000}).EnhanceMoonelectroBase,.07);
 for(const name of ['LaumaTalent1','NeferTalent1'])near(values(name,{em:400}).EnhanceMoonbloomBase,.07);
 for(const name of ['ZibaiTalent1','LinneaTalent1'])near(values(name,{def:2000}).EnhanceMoonCrystallizeBase,.14);
 assert.deepEqual(values('FlinsC6',{full_moon:false}),{});
 const aino=values('AinoC6',{full_moon:true});near(aino.EnhanceElectroCharged,.35);near(aino.EnhanceBloom,.35);near(aino.EnhanceMoonbloom,.35);assert.equal(aino.EnhanceHyperbloom,undefined);
 assert.deepEqual(values('AinoC6',{full_moon:true}, {...input,team_effects:{recipient_on_field:false}}),{});
 assert.throws(()=>values('LaumaSkillResMinus',{skill_level:0}),/无效/);
 for(const [n,p]of [['LaumaBurst',{em:null}],['ColumbinaC6',{elements:['Pyro']}],['LinneaC1',{stacks_available:1.5}]])assert.throws(()=>values(n,p),/无效|仅接受/);
 assert.ok(NATIVE_EFFECT_ATTRIBUTES.includes('ExtraDmgDirectMoonCrystallize'));
});
test('2 菈乌玛：实际等级表、月绽放本体与后加定额、普通绽放固定暴击和减抗',()=>{
 const buffs=[named('LaumaTalent1',{em:800}),named('LaumaTalent2',{mode:2}),named('LaumaSkillResMinus',{skill_level:10}),named('LaumaBurst',{em:800,skill_level:10,constellation:2,full_moon:true}),named('LaumaC6')];
 const x=direct('lunar-bloom',buffs,{owner:{id:'Nefer',em:200,critRate:.2,critDamage:1},scalingStat:1000,flatBonus:100,resistanceMultiplier:undefined,resistanceBeforeBuffs:.1});
 const r=calculateDirectLunarDamage(x);const n=(1000*1.14*(1+1200/2200+.4)+6400+100)*1.075*1.25;near(r.non_critical,n);near(r.expectation,n*1.36);
 near(values('LaumaSkillResMinus',{skill_level:15}).ResMinusHydro,.40);
 near(values('LaumaBurst',{em:100,skill_level:13,constellation:2}).ExtraDmgMoonbloom,872.3);
 near(values('LaumaBurst',{em:100,skill_level:13,constellation:2}).BloomFamilyFlat,1090.2);
 const exhausted=values('LaumaBurst',{stacks_available:0,constellation:2,full_moon:true});near(exhausted.ExtraDmgMoonbloom,0);near(exhausted.EnhanceMoonbloom,.4);
 const ordinary=calculateBloomFamilyDamage({kind:'bloom',owner:{id:'trigger',em:0,critRate:1,critDamage:9},levelBase:100,resistanceMultiplier:1,buffs:[named('LaumaBurst',{em:800,skill_level:10,constellation:2}),named('LaumaTalent2',{mode:1}),named('LaumaC6')]});
 near(ordinary.expectation,(200+8000)*1.15);near(ordinary.fixed_crit_rate,.15);near(ordinary.fixed_crit_damage,1);
 assert.equal(lunarParameters('lunar-electro',buffs).flatBonus,0);near(lunarParameters('lunar-electro',buffs).critRate,0);
 assert.throws(()=>calculateDirectLunarDamage({...x,resistanceMultiplier:1}),/同时填写/);
});
test('3 兹白、莉奈娅和叶洛亚：月结晶双定额、直伤限定、来源身份、消耗数量',()=>{
 const buffs=[named('ZibaiTalent1'),named('LinneaTalent1'),named('ZibaiC2'),named('LinneaC1',{def:2000}),named('IllugaQ',{em:100,skill_level:10,team_hydro_geo_count:2}),named('LinneaC6')];
 near(calculateDirectLunarDamage(direct('lunar-crystallize',buffs)).non_critical,(160*1.28*1.3+1500+502.66)*1.25);
 near(values('IllugaQ',{em:100,skill_level:10,team_hydro_geo_count:2}).ExtraDmgGeo,74.48);
 const participant=(id,element,buffs=[])=>({id,element,buffs,levelBase:100,em:0,critRate:0,critDamage:0});
 const team={resistanceMultiplier:1,participants:[participant('Zibai','Geo'),participant('hydro','Hydro')]};
 const normal=calculateLunarCrystallizeTeam(team).expectation;
 const qOnly={...team,participants:[participant('Zibai','Geo',[named('IllugaQ')]),participant('hydro','Hydro')]};near(calculateLunarCrystallizeTeam(qOnly).expectation,normal);
 near(calculateLunarCrystallizeTeam({...team,participants:[participant('Zibai','Geo',[named('LinneaC1',{def:2000})]),participant('hydro','Hydro')]}).expectation-normal,900);
 const hit=linneaCatalogHit({def:2000,c6:true,stacks_available:18},input);near(hit.flat,4500);assert.equal(hit.consumed,2);
 near(values('LinneaC1',{c6:true,stacks_available:1}).ExtraDmgMoonCrystallize,0);
 assert.throws(()=>values('LinneaC1',{hit_mode:1}),/莉奈娅自身/);
 near(values('LinneaC1',{def:2000,hit_mode:1,c6:false,nuke_stacks:5},{character:{name:'Linnea'}}).ExtraDmgDirectMoonCrystallize,15000);
 near(values('LinneaC4',{mode:2},{character:{name:'Linnea'}}).DEFPercentage,.5);
 near(values('LinneaC4',{mode:1},input).DEFPercentage,.25);
 assert.deepEqual(values('LinneaC4',{mode:1},{...input,team_effects:{recipient_on_field:false}}),{});
 assert.equal(lunarParameters('lunar-crystallize',[named('IllugaQ')],{recipientOnField:false}).flatBonus,0);
 assert.equal(lunarParameters('lunar-crystallize',[named('IllugaQ',{recipient_on_field:false})]).flatBonus,0);
 near(calculateDirectLunarDamage(direct('lunar-crystallize',[named('IllugaQ',{recipient_on_field:false})])).non_critical,160);
});
test('4 少女：生命转换、完整Q等级、C2三分支、命座加算和元素暴伤归属',()=>{
 near(values('ColumbinaP1',{hp:10000}).EnhanceMoonbloomBase,.02);near(values('ColumbinaP1',{hp:35000}).EnhanceMoonCrystallizeBase,.07);
 near(values('ColumbinaQ',{level:1}).EnhanceMoonReaction,.13);near(values('ColumbinaQ',{level:15}).EnhanceMoonReaction,.55);
 near(values('ColumbinaQ',{level:10},{...input,team_effects:{recipient_on_field:false}}).EnhanceMoonReaction,.4);
 assert.deepEqual(values('ColumbinaQ',{domain_active:false}),{});
 for(const [type,key,amount]of [[1,'ATKFixed',400],[2,'ElementalMastery',140],[3,'DEFFixed',400]])near(values('ColumbinaC2',{hp:40000,type_index:type})[key],amount);
 const self=values('ColumbinaC2',{hp:40000,type_index:1,full_moon:false},{character:{name:'Columbina'}});near(self.HPPercentage,.4);assert.equal(self.ATKFixed,undefined);
 const total=[0,.015,.085,.1,.115,.13,.2];for(let c=0;c<=6;c++)near(values('ColumbinaConstellation',{constellation:c}).ElevateMoonbloom,total[c]);
 const buffs=[named('ColumbinaP1'),named('ColumbinaQ'),named('ColumbinaConstellation',{constellation:6}),named('ColumbinaC6',{elements:['Geo','Hydro','Geo']})];
 const r=calculateDirectLunarDamage(direct('lunar-crystallize',buffs,{owner:{id:'Zibai',em:0,critRate:.5,critDamage:1}}));near(r.expectation,160*1.07*1.4*1.2*1.9);
 near(lunarParameters('lunar-bloom',[buffs[3]]).critDamage,0);near(values('ColumbinaC6',{elements:['Geo','Geo']}).CriticalDamageGeo,.8);
});
test('5 实际单次API绑定、参数回归、优化隔离与修改后面板语法',()=>{
 const api=withLunarDamageContexts({CalculatorInterface:{get_damage_analysis:()=>({normal:{expectation:7}})},OptimizeSingleWasm:{optimize:()=>[]}});
 const config={character:{name:'Vesna'},buffs:[named('LaumaBurst',{em:100,constellation:2}),named('LaumaTalent2',{mode:2}),named('MoonReactionDamageMultiplier',{p:150}),named('ElevateMoonbloom',{p:25})],direct_lunar_context:direct('lunar-bloom')};
 const expected=calculateDirectLunarDamage({...config.direct_lunar_context,buffs:config.buffs});near(api.CalculatorInterface.get_damage_analysis(config).direct_moonbloom.expectation,expected.expectation);
 const offField={character:{name:'Vesna'},buffs:[named('IllugaQ')],direct_lunar_context:direct('lunar-crystallize',[],{owner:{id:'Vesna',em:0,critRate:0,critDamage:0,recipientOnField:false}})};
 near(api.CalculatorInterface.get_damage_analysis(offField).direct_mooncrystallize.expectation,160);
 const bloom={character:{name:'Vesna'},buffs:[named('LaumaBurst',{em:100})],ordinary_bloom_context:{kind:'hyperbloom',owner:{id:'Vesna',em:0},levelBase:100,resistanceMultiplier:1}};
 near(api.CalculatorInterface.get_damage_analysis(bloom).hyperbloom.expectation,800);
 assert.throws(()=>api.OptimizeSingleWasm.optimize(config,[]),/仅支持单次/);assert.throws(()=>api.OptimizeSingleWasm.optimize(bloom,[]),/仅支持单次/);
 const compiler=createRequire(import.meta.url)('@vue/compiler-sfc');const file=new URL('../src/pages/NewArtifactPlanPage/LunarDamagePanel.vue',import.meta.url);const source=fs.readFileSync(file,'utf8');const p=compiler.parse(source);assert.equal(p.errors.length,0);compiler.compileScript(p.descriptor,{id:'lunar-characters'});assert.equal(compiler.compileTemplate({source:p.descriptor.template.content,filename:'LunarDamagePanel.vue',id:'lunar-characters'}).errors.length,0);
});
